// <auto-generated />
namespace Asp.Identity.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class possible_answers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(possible_answers));
        
        string IMigrationMetadata.Id
        {
            get { return "201705051654046_possible_answers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
